server:
  port: "8081"
database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: my_password
  name: fc2
  sslmode: disable
redis:  
  host: localhost   
  port: 6379        
  password: ""      
  db: 0             
kafka:
  bootstrap_servers: "localhost:9092"  
  topics:
    user_authenticate: "user-authenticate-topic"
    user_registered: "user-registered-topic"
    user_logged_out: "user-logged-out-topic"
    user_delete: "user-delete-topic"
  group_id: "auth-service-group"  