server:
  port: "8081"
  https_certificate: "../certifate.pem"
  https_key: "../key.pem"
database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: my_password
  name: fc2
  sslmode: disable